### ISSUE TITLE
Warning: Interpolation-only expressions are deprecated

### ISSUE THREAD

**Issue by Agilitytime** [ahoz/hcloud_terraform_ansible_provision#1]
Warning: Interpolation-only expressions are deprecated
 I using Terraform version 13.

when i Remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression it dosent work for the hetzner.tf.

Thanks,
Sebastian

**Comment by ahoz** [comment]
I will take a look into it.

**Comment by Agilitytime** [comment]
Thank You! 
i just can't get it to work

**Comment by ahoz** [comment]
Hi Sebatian,

thank you for noticing this bug. Indeed, i was using Terraform v0.12. After updating to version v0.13 it stopped working. The issue should now be fixed in the latest release: https://github.com/ahoz/hcloud_terraform_ansible_provision/releases/tag/673e459

Best Regards :)
Ahmet
